name: Sync to GitLab

on:
  push:
    branches:
      - main  # o la rama que desees sincronizar

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Clonar sin profundidad para evitar shallow update

      - name: Set up Git
        run: |
          git config --global user.email "manuteterocken@gmail.com"
          git config --global user.name "teterocken"
          git remote -v  # Verificar configuración de remotos

      - name: Pull from GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/teterocken/ProyectoMPS.git
          git fetch gitlab main  # Fetch the changes from GitLab
          git config pull.rebase false  # Configurar para hacer un merge
          git pull gitlab main --allow-unrelated-histories  # Hacer pull de los cambios remotos

      - name: Check for merge conflicts
        run: |
          if git ls-files -u | grep .; then
            echo "Merge conflicts detected. Please resolve them manually."
            exit 1
          fi

      - name: Commit changes if any
        run: |
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Merge changes from GitHub and GitLab"
          fi

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: git push gitlab main  # Hacer push de los cambios locales
