name: Sync to GitLab

on:
  push:
    branches:
      - main  # o la rama que desees sincronizar

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git remote -v  # Verificar configuración de remotos

      - name: Debug Git Config
        run: git config --list

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          echo "Adding remote GitLab"
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/tu-usuario/nombre-repositorio.git
          git remote -v  # Verificar configuración de remotos después de añadir
          git push gitlab main  # o la rama que desees sincronizar
